### ISSUE TITLE
Borland ILINK support not possible (order dependency)

### ISSUE THREAD

**Issue by greatwolf** [deplinenoise/tundra#145]
I'm looking to add borland's compiler toolset to Tundra but there's a few things that's not too clear to me.

I'm using `tundra\scripts\tundra\tools\*` as a template starting point replacing the env variables as I go. The borland toolchain makes a distinction between different builds and options. For example, console app vs window GUI app vs dll. Another is single-threaded app vs multi-threaded app. And yet another aspect is static-linking vs dynamic-linking to the runtime library.

What's the best way to encapsulate these options in the toolset lua file? Keep in mind certain options _must_ be used together to get a working executable so this needs to be enforced somehow. For example, if I'm building a multi-threaded app that's linked dynamically to the runtime lib then `-tWM -tWR` must be passed during compiling and `cw32mti.lib` must be included when linking. If I'm creating a console app, `c0x32.obj` needs to be linked. For a Win32 GUI app, `c0w32.obj` must be linked. Those 2 aspects are mutually exclusive. These various options must be combined together in the right way to produce a working executable.

What's the recommended way to create this abstraction toolset layer for Tundra so it's easy to use and configure?

**Comment by deplinenoise** [comment]
Closing out old issues that have no traction for now. If you'd like to work on this issue, we can just re-open.

**Comment by greatwolf** [comment]
This is fine, given that Borland/Embarcadero's 32-bit toolchain doesn't support C++11, modern C++ programming can't really be done with it.
