### ISSUE TITLE
Add precompiled header support for GCC and Clang compilers

### ISSUE THREAD

**Issue by upcaste** [deplinenoise/tundra#189]
Hey, I recently migrated to Tundra 2, works great so far ^_^.

Anyway, to get to the core of this issue, it'd be nice if we could get Tundra's existing PrecompiledHeader configuration block working for the GCC and Clang compilers. Currently, in generic-cpp.lua, it assumes that we're only interested in generating precompiled headers for MSVC, which have two inputs (C/C++ source file and a header file) and two outputs (an .obj for the translation unit, plus the .pch file).

With GCC and Clang there's only a single input (just the header) and a single ouput (a .ghc or .pch respectively). Furthermore, the .ghc or .pch file must be placed in the same directory as the original header file and have the same file name pattern as the original header file to enable the compilers to detect their existence.

I think supporting this would involve pulling out the current precompiled header node generation code from generic_cpp_setup in generic-cpp.lua, and implementing equivalent functionality inside of each concrete native C/C++ compiler script file.

We could also emulate MSVC's behavior for GCC/Clang with the output .obj file, and add a second node for the C/C++ source file in the non-PCH gen pass, in order to make it more consistent between the different compilers.

Any other thoughts on how we could best implement this feature?

**Comment by wgssmiddleditch** [comment]
> Does it work if we put the generated file in $(OBJECTDIR) somewhere and have that in the include path?

Yes. At least for Clang you can add the `-include-pch` option and point it directly to the compiled PCH, no matter where it lives.

[GCC's PCH documentation](https://gcc.gnu.org/onlinedocs/gcc/Precompiled-Headers.html) explicitly notes that you can use `-I` to search for compiled PCHs in different directories.

**Comment by bmharper** [comment]
This issue was fixed by 246fb12aff8d2f3e80d385b0bd46d35118739668. I think we can close the issue?
