### ISSUE TITLE
No support for -( archives -) or --start-group archives --end-group under Linux ld

### ISSUE THREAD

**Issue by hookenz** [deplinenoise/tundra#209]
Great project!  but it's missing a feature I could use.

I have a project ported from Windows that has some circular dependencies in some static libraries.

Without making major changes I can't link it using --start-group --end-group options.
However, there is no way to define this in tunrdra at the moment.

It'd be good to make this available.

I suggest that as well as  Depends = { }
We have Archive = { }  option for such a feature.

**Comment by deplinenoise** [comment]
Closing out old issues that have no traction for now. If you'd like to work on this issue, we can just re-open.
