### ISSUE TITLE
Group projects for IDE generation

### ISSUE THREAD

**Issue by emoon** [deplinenoise/tundra#242]
Something that would be useful is to set a group name on a project that can be used when generating IDE projects (for example tests would could be grouped under a a test/ "directory" as seen in MSVC)

**Comment by deplinenoise** [comment]
Isn't this covered already by the existing solution folder stuff?

On Jan 23, 2015, at 5:10, Daniel Collin <notifications@github.com> wrote:

Something that would be useful is to set a group name on a project that can
be used when generating IDE projects (for example tests would could be
grouped under a a test/ "directory" as seen in MSVC)

—
Reply to this email directly or view it on GitHub
<https://github.com/deplinenoise/tundra/issues/242>.

**Comment by emoon** [comment]
Not really as one still have your projects in one flat list. I would like to group the different projects under categories.

**Comment by deplinenoise** [comment]
Just so I understand, you want more than one level of folders in the solution? E.g.

```
Foo/ (folder)
  Bar/ (folder)
    Baz(project)
    Moo(project)
```

You can already do one level currently.

**Comment by emoon** [comment]
Ah. One level is fine (I just want a way to group the projects)

**Comment by deplinenoise** [comment]
OK; you can check out the fancyvs example to see how the existing stuff works!

**Comment by emoon** [comment]
Sweet! Thanks :)
