### ISSUE TITLE
Generated code split between debug and release

### ISSUE THREAD

**Issue by leidegre** [deplinenoise/tundra#244]
I have a custom `DefRule` for Google's Protocol Buffer files.

    DefRule {
      Name            = "Protobuf",
      Pass            = "CodeGeneration",
      ConfigInvariant = true,
      Command         = "$(OBJECTDIR)$(SEP)protoc$(PROGSUFFIX) --error_format=msvs --cpp_out=$(OBJECTDIR) $(PROTO_PATH:n:p-I) $(<)",
      ImplicitInputs  = { "$(OBJECTDIR)$(SEP)protoc$(PROGSUFFIX)" },
      Blueprint = {
        Include = { Type = "string", Required = false },
        Source = { Type = "table", Required = true },
      },
      Setup = function (env, data)
    		if data.Include then
    			env:set("PROTO_PATH", native.getcwd() .. "/" .. data.Include)
    		end
    		local outputs = {}
    		for _, inputFile in ipairs(data.Source) do
    			local f = path.get_filename_base(inputFile)
    			outputs[#outputs + 1] = "$(OBJECTDIR)/" .. f .. ".pb.h"
    			outputs[#outputs + 1] = "$(OBJECTDIR)/" .. f .. ".pb.cc"
    		end
        return {
          InputFiles  = data.Source,
          OutputFiles = outputs,
        }
      end,
    }

The above appears to work just fine but this is where it gets weird.

I invoke tundra like this `tundra2 -v win64-msvc-debug protofiles` which will tell it to build this unit:

    local protobuf_path = "lib/protobuf-2.4.1/src"
    StaticLibrary {
    	Name = "protofiles",
    	Pass = "CodeGeneration",
    	Env = {
    		CPPPATH = {
    			protobuf_path,
    			"$(OBJECTDIR)",
    		},
    	},
    	Propagate = {
    		Env = {
    			CPPPATH = {
    				protobuf_path,
    				"$(OBJECTDIR)",
    			},
    		},
    	},
    	Sources = {
    		Protobuf { 
    			Include = "src/win32/protofiles",
    			Source = Glob { 
    				Dir = "src/win32/protofiles", 
    				Extensions = { ".proto" } 
    			} 
    		}
    	},
    }

And here is what happens...

    Protobuf src\win32\protofiles\FileVersionInfo.proto src\win32\protofiles\Usage.proto
    t2-output\win64-msvc-release-default\protoc.exe --error_format=msvs --cpp_out=t2-output\win64-msvc-release-default -ID:\project\src\win32\protofiles D:\project\src\win32\protofiles\FileVersionInfo.proto D:\project\src\win32\protofiles\Usage.proto
    C++ t2-output\win64-msvc-release-default\FileVersionInfo.pb.cc
    "C:\Program Files (x86)\Microsoft Visual Studio 12.0\vc\bin\amd64\cl.exe" /c @RESPONSE|@|/D_WIN32 /DUNICODE /D_UNICODE /D_USING_V110_SDK71_ /D_WIN32_WINNT=0x501  /I"lib\\protobuf-2.4.1\\src" /I"t2-output\\win64-msvc-debug-default" /nologo /FS /FC /EHa /MDd /Od   /Zi /Fdt2-output\win64-msvc-debug-default\protofiles_ccpdb.pdb /FoD:\project\t2-output\win64-msvc-debug-default\__protofiles\t2-output\win64-msvc-release-default\FileVersionInfo.pb__cc.obj D:\project\t2-output\win64-msvc-release-default\FileVersionInfo.pb.cc
    C++ t2-output\win64-msvc-release-default\Usage.pb.cc
    "C:\Program Files (x86)\Microsoft Visual Studio 12.0\vc\bin\amd64\cl.exe" /c @RESPONSE|@|/D_WIN32 /DUNICODE /D_UNICODE /D_USING_V110_SDK71_ /D_WIN32_WINNT=0x501  /I"lib\\protobuf-2.4.1\\src" /I"t2-output\\win64-msvc-debug-default" /nologo /FS /FC /EHa /MDd /Od   /Zi /Fdt2-output\win64-msvc-debug-default\protofiles_ccpdb.pdb /FoD:\project\t2-output\win64-msvc-debug-default\__protofiles\t2-output\win64-msvc-release-default\Usage.pb__cc.obj D:\project\t2-output\win64-msvc-release-default\Usage.pb.cc
    FileVersionInfo.pb.cc
    Usage.pb.cc
    StaticLibrary t2-output\win64-msvc-debug-default\protofiles.lib
    "C:\Program Files (x86)\Microsoft Visual Studio 12.0\vc\bin\amd64\lib.exe" /nologo @RESPONSE|@|/MACHINE:X64 /out:"D:\\Project\\t2-output\\win64-msvc-debug-default\\protofiles.lib"

It's a wall of text, take a closer look at where the files end up. The output sources from protoc are put in the `t2-output\win64-msvc-release-default` dir but the object and library files correctly end up in `t2-output\win64-msvc-debug-default` (but no source files) since everything is specified using `$(OBJECTDIR)` in my `DefRule` how can it mix it like that? What's going on here? Why is the `t2-output\win64-msvc-release-default` dir being built at all when I tell tundra to build just `win64-msvc-debug`? Does it have anything to do with the way passes work or the `Always` function?

I think the header files is going to be a problem. They'll end up in the wrong folder.

EDIT: I deleted all tundra cache files and output directories and ran the build many times over. Always the same result.

**Comment by deplinenoise** [comment]
I think this is because you're using `ConfigInvariant = true` - that's saying the rule is the same for all configs. So Tundra chooses the first one arbitrarily to serve for all configs. It's a bug to use `$(OBJECTDIR)` in a rule like that, as it then isn't invariant per config.

**Comment by leidegre** [comment]
Cool, thanks! Looks right now.
