### ISSUE TITLE
Custom unit types

### ISSUE THREAD

**Issue by leidegre** [deplinenoise/tundra#245]
I'm running in two some issues trying to setup a unit type for building .NET modules (.netmodule).

I've started with the example in the documentation but ran into issues with the environment being nil. I then noticed that it was calling `env:make_node` while the syntax extensions for the `dotnet` tool use `depgraph.make_node`. I started working of the syntax extension but then ran into another issue.

```
[E] duplicate node guids: Dummy node for nosecure and Dummy node for nosecure share common GUID
```

I found an older issue reported by Ben (https://github.com/deplinenoise/tundra/issues/152) which has been closed with a simple workaround so I attempted this myself. However, it did nothing.

```
[E] duplicate node guids: dummy node for NLevelDBNetModule (2) and dummy node for NLevelDBNetModule (1) share common GUID (abb42ef4dd54cc51f562e67402f85d07)
```

Here's the full script of the new unit that I'm trying to write:

```
module(..., package.seeall)

local util = require "tundra.util"
local nodegen = require "tundra.nodegen"
local depgraph = require "tundra.depgraph"

-- Create a metatable for this evaluator
local _mt = nodegen.create_eval_subclass {
}

-- Describe the syntactic form of the unit. This describes the data that is
-- passed into create_dag below after checking.
local blueprint = {
    Name = {
      Required = true,
      Help = "Set output (base) filename",
      Type = "string",
    },
    Sources = {
        Required = true,
        Help = "List of sources files",
        Type = "source_list",
                ExtensionKey = "DOTNET_SUFFIXES"
    },
}

local external_counter = 1
function _mt:create_dag(env, data, deps)
        local label = string.format("dummy node for %s (%d)", data.Name, external_counter)
        external_counter = external_counter + 1
    return depgraph.make_node {
                Env = env,
        Label = label,
                Pass = data.Pass,
        Action = "$(CSC)",
        Inputs = data.Sources,
        Outputs = { "$(OBJECTROOT)/" .. data.Name .. ".netmodule" },
        Dependencies = deps,
    }
end

-- Add evaluator
nodegen.add_evaluator("DotNetModule", _mt, blueprint)
```

**Comment by deplinenoise** [comment]
Are you sure the DAG generator has actually rerun? The error message about the duplicate GUIDs below seems to indicate that your extra number decorations are not actually added to the names of the DAG nodes.

**Comment by leidegre** [comment]
I'll do more tests. I managed to extend the existing dotnet tool chain with a .netmodule unit I thought I was doing the exact same thing but I must be missing something.

**Comment by deplinenoise** [comment]
Yeah, or you can run with `-f` to force DAG regeneration.

**Comment by deplinenoise** [comment]
(However if that fixes it it's a bug, so I'd appreciate repro steps in that case!)

**Comment by leidegre** [comment]
Yeah, I'll try to find a minimal repo step. I later stepped away from using .netmodules entirely but I'll get around to it eventually.

**Comment by leidegre** [comment]
Sorry, no longer working on this either. IOU at least 1 decent bug report.
