### ISSUE TITLE
Generated code not feed into next step

### ISSUE THREAD

**Issue by leidegre** [deplinenoise/tundra#246]
I have `DefRule` that I use to convert a text file into a global string.

    DefRule {
      Name            = "StringCompiler",
      Pass            = "CodeGeneration",
      ConfigInvariant = false,
      Command         = "$(OBJECTDIR)$(SEP)strc$(PROGSUFFIX) -out_dir $(OBJECTDIR) $(<)",
      ImplicitInputs  = { "$(OBJECTDIR)$(SEP)strc$(PROGSUFFIX)" },
      Blueprint = {
        InputFiles = { Type = "table", Required = true },
      },
      Setup = function (env, data)
    		local ouput_files = {}
    		for _, v in ipairs(data.InputFiles) do
    			local output_file = "$(OBJECTDIR)/" .. path.get_filename_base(v) .. ".cpp"
    			ouput_files[#ouput_files] = output_file
    			print("STRC-OUT: " .. output_file) --debug
    		end
        return {
          InputFiles = data.InputFiles,
          OutputFiles = ouput_files,
        }
      end,
    }

I later use the above StringCompiler  `strc` like this

    StaticLibrary {
    	Name = "textlib",
    	Depends = {
    		...
    	},
    	Sources = { 
    		Glob { 
    			...
    		},
    		StringCompiler {
    			InputFiles = { 
    				"src/win32/text/x.txt", 
    				"src/win32/text/y.txt",
    			},
    		},
    	},
    	...

The code gets generated but I get linker errors and I cannot see that the build has generated any object files for the output. I have a similar `DefRule` for .proto files which does about the same thing and it works just fine.

Any advice where to look?

**Edit:** I have three passes in total, two explicit and the default pass. `strc` is always built in the first pass, there's a code generation pass and lastly I want any outputs to be feed into this `textlib` library.

**Edit 2:** The generated files are not showing up in the generated projects either. This is not the case with the .proto files so I probably missed something, just don't know what.

**Edit 3:** Here's a complete repo (https://gist.github.com/leidegre/3d11e16a7565083b8a47) on Windows/Visual Studio 2013.

**Comment by deplinenoise** [comment]
I tried your repro (thanks!) - the bug is that your output file array is not being set up correctly:

Try adding a +1 like this:

```lua
    ouput_files[#ouput_files + 1] = output_file
```

**Comment by leidegre** [comment]
I must have gotten blind in the process, thanks for the help. I can never get used to those one based indexes.
