### ISSUE TITLE
What's the simplest way to add an implicit input to a node?

### ISSUE THREAD

**Issue by leidegre** [deplinenoise/tundra#249]
I have a Win32 resource (`.rc`) file that specifies a file as a resource. I'd like to add that file as an implicit input to the .rc file node. The resource file looks like this.

```
"SOME_RESOURCE_NAME" RCDATA "SomeFile.txt"
```

What I would like to be able to do is basically this (simple and to the point).

```
{ "Resources.rc", ImplicitInputs = { "SomeFile.txt" } }
```

And have that table be passed to the eventual `make_node` call together with any other `ImplicitInputs`. However, file names get passed around as string and a lot of code is treating file names as just string making files names complex or adding function call parameters to the setup feels like a lot of work.

Ideas, anyone?

**Comment by deplinenoise** [comment]
Normally you'd do this by registering an implicit dependency scanner for
your type. I'm pretty sure rc targets use the cpp scanner.

Maybe you could alter the rc scanner to also go find these other files. The
cpp scanner is implemented in native code for performance reasons. Adding
optional handling of RC keywords in there might be ok.

On Apr 23, 2015, at 7:59, John Leidegren <notifications@github.com> wrote:

I have a Win32 resource (.rc) file that specifies a file as a resource. I'd
like to add that file as an implicit input to the .rc file node. The
resource file looks like this.

"SOME_RESOURCE_NAME" RCDATA "SomeFile.txt"

What I would like to be able to do is basically this (simple and to the
point).

{ "Resources.rc", ImplicitInputs = { "SomeFile.txt" } }

And have that table be passed to the eventual make_node call together with
any other ImplicitInputs. However, file names get passed around as string
and a lot of code is treating file names as just string making files names
complex or adding function call parameters to the setup feels like a lot of
work.

Ideas, anyone?

—
Reply to this email directly or view it on GitHub
<https://github.com/deplinenoise/tundra/issues/249>.

**Comment by leidegre** [comment]
Thought as much. I'll take a closer look.
