### ISSUE TITLE
release tarball doesn't compile when using make

### ISSUE THREAD

**Issue by twoscomplement** [deplinenoise/tundra#256]
Building from https://github.com/deplinenoise/tundra/archive/v2.0-beta11.tar.gz :

> make: *** No rule to make target '.git/refs/heads/', needed by 'build/git_version_.c'.  Stop.

Just so you know. Not really sure what an appropriate fix would be.

For now I'll build from a git checkout.

**Comment by deplinenoise** [comment]
Dupe/related to #226
