### ISSUE TITLE
mmap failed

### ISSUE THREAD

**Issue by jurgen-kluft** [deplinenoise/tundra#262]
Windows 7 - 64bit
24 GB
Intel(R) Core(TM) i7-4770 CPU @ 3.40GHZ

[D] PID 15888 successfully locked d:\Dev.Bitbucket\xunittest
[D] .tundra2.dag: mmap failed
[D] regenerating DAG data
"C:\Program Files\Tundra 2.0\bin\t2-lua.exe" generate-dag tundra.lua .tundra2.dag.json
Build script execution failed
...rogram Files\Tundra 2.0\scripts\tundra\buildfile.lua:166: assertion failed!
stack traceback:
        [C]: in function 'assert'
        ...rogram Files\Tundra 2.0\scripts\tundra\buildfile.lua:166: in function 'Build'
        [string "tundra.lua"]:1: in main chunk
        [C]: in function 'xpcall'
        ...rogram Files\Tundra 2.0\scripts\tundra\buildfile.lua:242: in function 'run'
        C:\Program Files\Tundra 2.0\scripts\tundra\boot.lua:93: in function 'generate_dag_data'
        C:\Program Files\Tundra 2.0\scripts\tundra.lua:8: in function 'action'
        C:\Program Files\Tundra 2.0\scripts\tundra.lua:38: in function <C:\Program Files\Tundra 2.0\scripts\tundra.lua:22>
        (tail call): ?
[E] DAG generator driver failed: "C:\Program Files\Tundra 2.0\bin\t2-lua.exe" generate-dag tundra.lua .tundra2.dag.json
*** Build failed to setup error (0.05 seconds)

**Comment by deplinenoise** [comment]
The error is not the best one, but it appears that the assert in `buildfile.lua:166` is due to a missing `Name` on a variant. Maybe double check your `tundra.lua` file for mistakes?

**Comment by jurgen-kluft** [comment]
Yes, you are right, it was a mistake in `tundra.lua`, i have succesfully run the helloworld example and am now using that as a base.

Sorry for the noise...
