### ISSUE TITLE
Mac OSX; how to build and run tundra

### ISSUE THREAD

**Issue by jurgen-kluft** [deplinenoise/tundra#264]
Are there any hints on how to build the binaries for OSX ?
I would like to try and work with tundra on OSX.

**Comment by emoon** [comment]
Run make in the root of the Tundra source

**Comment by emoon** [comment]
This is covered in https://github.com/deplinenoise/tundra/blob/master/doc/manual.asciidoc and the "Installing from source" section

**Comment by jurgen-kluft** [comment]
1. git clone https://github.com/deplinenoise/tundra.git
2. make
3. make install

The above worked, now using tundra on OSX.

Thanks!
