### ISSUE TITLE
ide generator

### ISSUE THREAD

**Issue by questor** [deplinenoise/tundra#265]
I've written a new ide-generator for qtcreator, but not with the intend to be able to trigger builds from qtcreator but to be able to use the c++ refactoring and intellisense support from it (with working project-structures). so it's only a half-working solution and not comparable to the msvc-ide-generator which is a complete wrapper. if it's of interest for you I can create a pull request with it so that you can inspect it (currently it's not checked in anywhere).
writing something similar for sublime text should also be very easy....

**Comment by questor** [comment]
here is the commit into my fork for review: https://github.com/questor/tundra/commit/6752f96c431e1f55161969bae643089c94681b40

**Comment by deplinenoise** [comment]
If it can actually build the code I'd be interested in bringing it back. At least people looking for QT Creator should be able to find your stuff via this issue in the meantime.

Aside: The IDE creators haven't received a lot of love and they have a lot of copy pasta.. I wonder if we couldn't remove 75% of the code and move that into a common helper module.
