### ISSUE TITLE
DefRule Command modification

### ISSUE THREAD

**Issue by questor** [deplinenoise/tundra#267]
I've written an own defrule for the protobuf-compiler:
DefRule {
   Name = "ProtoC",
   Pass = "CodeGeneration",
   Command = "$(PROTOCOMPILER) --cpp_out=$(OBJECTDIR) $(<)",
   ImplicitInputs = { "$(PROTOCOMPILER)" },

   Blueprint = {
      ProtoFile = { Required = true, Type = "string", Help = "Input filename" },
   },
   Setup = function(env, data)
      return {
         InputFiles  = { data.ProtoFile },
         OutputFiles = { 
            "$(OBJECTDIR)/"..string.gsub(data.ProtoFile, ".proto", ".pb.h"),
            "$(OBJECTDIR)/"..string.gsub(data.ProtoFile, ".proto", ".pb.cc"),
         }
      }
   end,
}

bug it doesn't work (tundra works, but protoc not ;) ) because the protoc needs to have as an argument the directory from the source file. the plain command currently sent to a shell is:

t2-output/win32-msvc-debug-default/protoc.exe --cpp_out=t2-output/win32msvc-debug-default d:\projects\test\test.proto

but I need an additional argument "--proto_path=d:\projects\test" to make the proto-compiler happy... how can I get this in my defrule? I think I need to modify the command-string on the fly with the directory from the source file, but I have no idea how to set it during compilation....

**Comment by deplinenoise** [comment]
You can use `$(VAR:D)` to just keep the directory part of any path. See the section on variable interpolation in the manual. For example, `$(<:D)` will interpolate to the directory containing the input file.
