### ISSUE TITLE
Visual C++ Build Tools not detected

### ISSUE THREAD

**Issue by ricka-github** [deplinenoise/tundra#272]
Visual C++ Build Tools preview can be downloaded from http://go.microsoft.com/fwlink/?LinkId=691132

This is a standalone compiler without the Visual Studio IDE. Tundra does not detect that this is installed.

**Comment by leidegre** [comment]
That's probably because they way we detect a Visual Studio toolchain is very different from the way this bundle from Microsoft works. 

Would you mind doing some leg work? We need to know what folder structure Microsoft is using for this release and how it relates to any SDK.

**Comment by ricka-github** [comment]
That is indeed what is happening. I did attempt to find a nice way to detect the presence of the Build Tools, but wasn’t able to find anything that is guaranteed to work. I gave up after that and moved back to the regular Visual Studio installs, so this issue isn’t pressing. I’m willing to take a look again at some point though.

Cheers,
Rick

**Comment by deplinenoise** [comment]
Closed as part of e07b12ac87bcc3f17d1d7e3e0c2c96c8bb3815af
