### ISSUE TITLE
New release version?

### ISSUE THREAD

**Issue by kainjow** [deplinenoise/tundra#285]
Seems like it's been in 2.0 beta for years. Can a final version be released? You can always push bug fix releases :)

The main reason I'm asking is I'm trying to add this project to [Homebrew](http://brew.sh) (see [here](https://github.com/Homebrew/homebrew-core/pull/9172)) but they require a stable tag/release for the version.

**Comment by deplinenoise** [comment]
Sure, I can tag this 2.0 as final, no worries.

**Comment by deplinenoise** [comment]
tag v2.0 is now a thing

**Comment by kainjow** [comment]
Awesome, thanks!
