### ISSUE TITLE
MSYS2 compilation fails

### ISSUE THREAD

**Issue by khmseu** [deplinenoise/tundra#290]
There are a number of smaller issues, but the big thing seems to be that MSYS2 (based on MINGW-w64 and a pacman-based package system, see msys2.org) tries to be more unixy (even defines __unix__), and therefore comes standard with winpthreads and lacks many of the usual MS interfaces, such as _beginthreadex. (The smaller issues mainly boil down to, if there's a CRT style function that is the equivalent of a POSIX function, offer only the POSIX API.)

**Comment by deplinenoise** [comment]
OK, thanks for the report. Do you feel like fixing it up? I produce my Windows binaries using cross compilation, so I don't actively use the Windows build environment.

**Comment by deplinenoise** [comment]
Closing this - I have no interest in this particular way of building Tundra, as there are official Windows binaries available already. If anyone feels like fixing this, feel free.
