### ISSUE TITLE
How to add a private toolchain (or any other lua script)

### ISSUE THREAD

**Issue by bmharper** [deplinenoise/tundra#293]
I have two cases where I need to make a tweaked toolchain - `clang-analyze`, and `afl`. In both cases, these programs work by replacing clang (or gcc) with their own wrapper program, which runs the regular compiler, and then add their own magic on top of that.

When using tundra, is there some official mechanism for defining your own toolchain (similar to `clang.lua`, or `gcc.lua`), which is part of your source code tree, and not part of the stock tundra distribution?

The best thing I've come up with so far is this (example here is for `afl`):
1. Create a file in my project: `build/tundra/tools/afl.lua`
2. Add a new Config that uses the `afl` toolchain.
3. Run tundra like so, to compile my project called "Test": <code>TUNDRA_LUA_PATH=\`pwd\`/build/?.lua tundra2 linux-afl-release Test</code>

It would be useful if one didn't need to setup the TUNDRA_LUA_PATH environment variable. Does it make sense that one could add some kind of lua call, which would add a new directory to the lua search path? You could then call that function at the top of your `tundra.lua` file, to add in your project-specific lua scripts.

I know this may seem a bit pedantic - I mean what's wrong with just setting TUNDRA_LUA_PATH for this niche case? However, I think it would be a good principle if one could easily add extra augmentations on top of tundra, in the form of lua scripts that are private to the source tree.

`afl.lua` contents:
```lua
module(..., package.seeall)

function apply(env, options)
  tundra.unitgen.load_toolset("gcc", env)

  env:set_many {
    ["CC"] = "/home/ben/dev/afl-2.51b/afl-clang",
    ["CXX"] = "/home/ben/dev/afl-2.51b/afl-clang++",
    ["LD"] = "/home/ben/dev/afl-2.51b/afl-clang",
  }
end
```

**Comment by deplinenoise** [comment]
You can add tool paths using the ScriptDir property.  This way they’re loaded just like built in tools and there’s no need for env hacks. Let me know if this doesn’t work for you.

**Comment by deplinenoise** [comment]
Sorry, ScriptDirs is the appropriate spelling. It adds to the Lua path and anything found there will be importable just like built in tools.

**Comment by bmharper** [comment]
Thanks - that's exactly what I was looking for. Sent a one character PR that fixes the typo in the manual.
