### ISSUE TITLE
Please update Brew package for Mac

### ISSUE THREAD

**Issue by jurgen-kluft** [deplinenoise/tundra#305]
Current version of Tundra in Brew is 2.01

**Comment by deplinenoise** [comment]
I'd love to, but the Tundra formula was contributed by someone else. The brew project frowns upon project owners pushing their own stuff, so someone else will have to submit a PR to them with the version bump.

**Comment by leidegre** [comment]
@jurgen-kluft try paging @kainjow

**Comment by kainjow** [comment]
I no longer use Tundra. However looks like you should just be able to update the url and sha256 fields.

**Comment by deplinenoise** [comment]
This looks like it's been updated upstream in homebrew to 2.06, so someone is tracking Tundra's releases now. Closing.
