### ISSUE TITLE
Relicensing tundra under MIT license

### ISSUE THREAD

**Issue by lucasmeijer** [deplinenoise/tundra#306]
Hey,

In order to make it easier for tundra to be adopted, I'd like to investigate the possibility of relicensing tundra under the MIT license, so that people writing other frontends for tundra do not have to worry about the GPL requirements travelling to the frontend code.

I've talked with @deplinenoise about it, and he supports the idea if I do the legwork of chasing down all contributors.  

This issue does that.   My question to all people that have landed a PR into the tundra repo:  Would you be willing to license the code you've contributed under the MIT license, so that we can make the entire repo MIT.  I hope you will, tundra is an amazing build system and I'd love to be able to use it everywhere.  If you do, simply replying on this issue with "I license all my contributions in the tundra repository under the MIT license" would suffice.

Thanks, Lucas

@leidegre 
@jsvennevid 
@jonaskje 
@jwtowner 
@uucidl 
@rudkx 
@emoon 
@bmharper 
@greatwolf 
@teddemunnik 
@mattrudder 
@Patuti 
@twoscomplement 
@aras-p

**Comment by jsvennevid** [comment]
I license all my contributions in the tundra repository under the MIT license.

**Comment by rudkx** [comment]
I license all my contributions in the tundra repository under the MIT license.

**Comment by jwtowner** [comment]
I license all my contributions in the tundra repository under the MIT license.

**Comment by Patuti** [comment]
I license all my contributions in the tundra repository under the MIT
license

**Comment by mattrudder** [comment]
I license all my contributions in the tundra repository under the MIT license.

**Comment by bmharper** [comment]
I license all my contributions in the tundra repository under the MIT license

**Comment by emoon** [comment]
I license all my contributions in the tundra repository under the MIT license.

**Comment by leidegre** [comment]
I license all my contributions in the tundra repository under the MIT license.

**Comment by aras-p** [comment]
I license all my contributions in the tundra repository under the MIT license.

**Comment by jonaskje** [comment]
I license all my contributions in the tundra repository under the MIT license.

-Jonas

**Comment by teddemunnik** [comment]
I license all my contributions in the tundra repository under the MIT license.

**Comment by twoscomplement** [comment]
I license all my contributions in the tundra repository under the MIT license.

**Comment by uucidl** [comment]
I license all my contributions in the tundra repository under the MIT license.
