### ISSUE TITLE
Tundra prematurely stops looking for "Depends"

### ISSUE THREAD

**Issue by leidegre** [deplinenoise/tundra#340]
I have a unit definition like below where there's a `nil` value in `Depends` which results in a linker error. If I move the `package_deps[libname]` last in the dependency list it works. I don't know if this is intentional or not but it caused an issue for me since I have this "convention" based approach to generate units based how I've organized stuff on disk. I got a linker error because sometimes the `package_deps` table doesn't have any deps for `libname`.

I can work around this by moving it to the end of the `Depends` table/list or by change the line to `package_deps[libname] or {}`, either is fine.

```lua
Program {
    Name = testname,
    Depends = {
        package_deps[libname], -- must be last because if nil tundra will stop looking for more deps...  
        libname, -- implicit
        "libtest",
        "win32", -- Windows specific???
    },
    Sources = {
        test[2]
    }
}
```

If this is not intentional I think Tundra should either crash with appropriate error or keep looking for dependencies in the list even if some of them are nil. Crashing (or at the very least emit a warning) might be appropriate because it could be a mistake if you have a local that is holding on to some dep information.

I'll happily commit to doing some work here If I can get some direction and a place to start.

**Comment by leidegre** [comment]
I put together a minimap repo [here](https://gist.github.com/leidegre/8e464c6fef609b4e2e7612d83e3c332b).

**Comment by deplinenoise** [comment]
This is an issue with Lua "arrays" in general, and `ipairs` specifically. For example:

```lua
a = { nil, 1, 2, 3 }
for _, val in ipairs(a) do
  print(val)
end
```

Will not print anything. The reason is that ipairs probes the table for successive keys but stops when it finds `nil`.

To work around your case, you have a few options:

* Use a nested table with a `Config` that never matches anything
* Use a function around your `Depends` lists to sanitize the `nil`s away
* Probably more options I can't think of right now

**Comment by deplinenoise** [comment]
Marking will not fix, as this is a Lua issue.

**Comment by deplinenoise** [comment]
That said, if you do want to attempt a fix, you could look here:

https://stackoverflow.com/questions/40441508/how-to-represent-nil-in-a-table

We'd have to rewrite the entire array/list utility library to not use `ipairs` directly, but instead handwrite loops and/or represent `nil` some other way, which is pretty awkward.

**Comment by leidegre** [comment]
Okay, if this is deeply engrained in how Lua works then it's just a quirk. I didn't know Lua operated this way. It sounds like a lot of grunt work for small win. There are many ways to workaround this issue and I'm fine with that.

**Comment by leidegre** [comment]
Maybe something like this?

```lua
tbl = {1,2,3,nil,5,6,7}

n = 1
for k,v in ipairs(tbl) do
  print(k, v)
  n = n + 1
end

print(#tbl, n)

if n < #tbl then
  print("warning: incomplete depends. unit xyz might be missing depedencies due to a nil value in the depends table")
end
```

**Comment by deplinenoise** [comment]
Yeah. Maybe worth putting something like this in utils and calling it for input arrays, discarding `nil` as appropriate?
